# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1f68f9451f03224dd4c12b823a75fc53b3d9553a2f9cc342b1c06a749e7f16110906fd928ee51b0ab37e8d7e1e2c808bbacac3a4153cd7bee7bc7e6459c4d68e

test:
  secret_key_base: 16738b19dc27f1b7b081b8b8b55acaa7d5ec09888174e5426b818fde99ac8a2793444864cc0ca22a9512ded688c4ae4c3d5ec571181d22a7d5d163afb83511fb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
